import { readFile, mkdir, writeFile } from 'node:fs/promises';
const artifact = JSON.parse(await readFile(new URL('../contracts/out/CapitalController.sol/CapitalController.json', import.meta.url), 'utf8'));
const target = new URL('../packages/sdk/src/abi.ts', import.meta.url);
await mkdir(new URL('../packages/sdk/src/', import.meta.url), { recursive: true });
await writeFile(target, `// Generated by scripts/generate-abi.mjs from the compiled project contract.\nexport const capitalControllerAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`);
