import type {
  CapitalActivity,
  DashboardData,
  Policy,
  TokenAmount,
  VaultNode,
} from "@/lib/dashboard-types";

const units = (rawAmount: string, symbol: string): TokenAmount => ({
  rawAmount,
  decimals: 2,
  symbol,
});

const rootPolicy: Policy = {
  permissions: ["delegate", "swap", "manage-liquidity", "collect-fees", "exit-liquidity", "reclaim"],
  allowedTokens: ["ACT-A", "ACT-B"],
  maxActionAmount: units("2500000", "ACT-A"),
  expiresAt: "2026-12-31T23:59:59.000Z",
};

const marketPolicy: Policy = {
  permissions: ["swap", "manage-liquidity", "collect-fees", "exit-liquidity"],
  allowedTokens: ["ACT-A", "ACT-B"],
  maxActionAmount: units("1250000", "ACT-A"),
  expiresAt: "2026-11-30T23:59:59.000Z",
};

const researchPolicy: Policy = {
  permissions: ["swap"],
  allowedTokens: ["ACT-A"],
  maxActionAmount: units("400000", "ACT-A"),
  expiresAt: "2026-10-31T23:59:59.000Z",
};

const scoutPolicy: Policy = {
  permissions: ["swap"],
  allowedTokens: ["ACT-A"],
  maxActionAmount: units("150000", "ACT-A"),
  expiresAt: "2026-10-18T23:59:59.000Z",
};

const previewSource = "preview" as const;

export const previewNodes: readonly VaultNode[] = [
  {
    id: "root",
    parentId: null,
    rootId: "root",
    ensName: "cedar.preview",
    label: "Cedar desk",
    agentAddress: "0x71e4…A91c",
    vaultAddress: "0x9b20…44d2",
    depth: 0,
    state: "active",
    runtime: "not-connected",
    freeCapital: [units("1462500", "ACT-A"), units("892400", "ACT-B")],
    totalBalance: [units("2862500", "ACT-A"), units("1292400", "ACT-B")],
    localPolicy: rootPolicy,
    inheritedConstraints: [],
    effectivePolicy: rootPolicy,
    source: previewSource,
  },
  {
    id: "market",
    parentId: "root",
    rootId: "root",
    ensName: "market.cedar.preview",
    label: "Market maker",
    agentAddress: "0x0e55…7F11",
    vaultAddress: "0xc450…C806",
    depth: 1,
    state: "active",
    runtime: "not-connected",
    freeCapital: [units("370000", "ACT-A"), units("182500", "ACT-B")],
    totalBalance: [units("1060000", "ACT-A"), units("382500", "ACT-B")],
    localPolicy: marketPolicy,
    inheritedConstraints: [{ ancestorId: "root", ancestorLabel: "Cedar desk", policy: rootPolicy }],
    effectivePolicy: marketPolicy,
    source: previewSource,
  },
  {
    id: "scout",
    parentId: "market",
    rootId: "root",
    ensName: "scout.market.cedar.preview",
    label: "Spread scout",
    agentAddress: "0x339a…EF05",
    vaultAddress: "0x5C87…0B13",
    depth: 2,
    state: "active",
    runtime: "not-connected",
    freeCapital: [units("83000", "ACT-A"), units("46100", "ACT-B")],
    totalBalance: [units("208000", "ACT-A"), units("96100", "ACT-B")],
    localPolicy: scoutPolicy,
    inheritedConstraints: [
      { ancestorId: "root", ancestorLabel: "Cedar desk", policy: rootPolicy },
      { ancestorId: "market", ancestorLabel: "Market maker", policy: marketPolicy },
    ],
    effectivePolicy: scoutPolicy,
    source: previewSource,
  },
  {
    id: "liquidity",
    parentId: "market",
    rootId: "root",
    ensName: "liquidity.market.cedar.preview",
    label: "Liquidity steward",
    agentAddress: "0x3a2f…6c99",
    vaultAddress: "0x3190…c8e7",
    depth: 2,
    state: "active",
    runtime: "not-connected",
    freeCapital: [units("196000", "ACT-A"), units("136000", "ACT-B")],
    totalBalance: [units("596000", "ACT-A"), units("336000", "ACT-B")],
    localPolicy: marketPolicy,
    inheritedConstraints: [
      { ancestorId: "root", ancestorLabel: "Cedar desk", policy: rootPolicy },
      { ancestorId: "market", ancestorLabel: "Market maker", policy: marketPolicy },
    ],
    effectivePolicy: marketPolicy,
    source: previewSource,
  },
  {
    id: "research",
    parentId: "root",
    rootId: "root",
    ensName: "research.cedar.preview",
    label: "Signal research",
    agentAddress: "0x883c…2e71",
    vaultAddress: "0x7701…C192",
    depth: 1,
    state: "active",
    runtime: "not-connected",
    freeCapital: [units("250000", "ACT-A")],
    totalBalance: [units("650000", "ACT-A")],
    localPolicy: researchPolicy,
    inheritedConstraints: [{ ancestorId: "root", ancestorLabel: "Cedar desk", policy: rootPolicy }],
    effectivePolicy: researchPolicy,
    source: previewSource,
  },
  {
    id: "oracle",
    parentId: "research",
    rootId: "root",
    ensName: "oracle.research.cedar.preview",
    label: "Oracle watcher",
    agentAddress: "0x8ac7…2dd4",
    vaultAddress: "0x8053…F31a",
    depth: 2,
    state: "active",
    runtime: "not-connected",
    freeCapital: [units("125000", "ACT-A")],
    totalBalance: [units("285000", "ACT-A")],
    localPolicy: scoutPolicy,
    inheritedConstraints: [
      { ancestorId: "root", ancestorLabel: "Cedar desk", policy: rootPolicy },
      { ancestorId: "research", ancestorLabel: "Signal research", policy: researchPolicy },
    ],
    effectivePolicy: scoutPolicy,
    source: previewSource,
  },
];

const previewActivity: readonly CapitalActivity[] = [
  {
    id: "a-01",
    kind: "capital-assigned",
    nodeId: "market",
    nodeLabel: "Market maker",
    description: "Capital delegated from Cedar desk",
    amount: units("690000", "ACT-A"),
    timestamp: "2026-09-25T09:42:00.000Z",
    source: previewSource,
  },
  {
    id: "a-02",
    kind: "swap",
    nodeId: "scout",
    nodeLabel: "Spread scout",
    description: "Preview swap · ACT-A → ACT-B",
    amount: units("8200", "ACT-A"),
    timestamp: "2026-09-25T09:16:00.000Z",
    source: previewSource,
  },
  {
    id: "a-03",
    kind: "position-opened",
    nodeId: "liquidity",
    nodeLabel: "Liquidity steward",
    description: "Opened ACT-A / ACT-B position",
    timestamp: "2026-09-25T08:51:00.000Z",
    source: previewSource,
  },
  {
    id: "a-04",
    kind: "policy-tightened",
    nodeId: "oracle",
    nodeLabel: "Oracle watcher",
    description: "Action ceiling narrowed by parent",
    timestamp: "2026-09-24T17:08:00.000Z",
    source: previewSource,
  },
];

export const previewDashboard: DashboardData = {
  source: previewSource,
  chainId: 11155111,
  rootId: "root",
  contractsConfigured: false,
  nodes: previewNodes,
  activity: previewActivity,
  positions: [
    {
      id: "#018",
      poolLabel: "ACT-A / ACT-B · 0.30%",
      state: "open",
      liquidity: "42,800",
      token0: units("138500", "ACT-A"),
      token1: units("92200", "ACT-B"),
      fees0: units("1260", "ACT-A"),
      fees1: units("830", "ACT-B"),
      source: previewSource,
    },
  ],
};
