import type {
  CapitalActivity,
  DashboardData,
  Policy,
  TokenAmount,
  VaultNode,
} from "@/lib/dashboard-types";

// Illustrative values are intentionally small and cannot be mistaken for funded vaults.
const units = (scaled: string, symbol: string): TokenAmount => ({
  rawAmount: (BigInt(scaled) * 10n).toString(),
  decimals: 6,
  symbol,
});

const previewPoolId = `0x${"0".repeat(64)}` as const;

const rootPolicy: Policy = {
  permissions: ["delegate", "swap", "manage-liquidity", "collect-fees", "exit-liquidity", "restrict", "reclaim"],
  allowedTokens: ["Fictional USDC", "DEMO-USD"],
  maxActionAmounts: [units("2500000", "Fictional USDC"), units("2500000", "DEMO-USD")],
  expiresAt: "2026-12-31T23:59:59.000Z",
  poolId: previewPoolId,
};

const marketPolicy: Policy = {
  permissions: ["delegate", "swap", "manage-liquidity", "collect-fees", "exit-liquidity"],
  allowedTokens: ["Fictional USDC", "DEMO-USD"],
  maxActionAmounts: [units("1250000", "Fictional USDC"), units("1250000", "DEMO-USD")],
  expiresAt: "2026-11-30T23:59:59.000Z",
  poolId: previewPoolId,
};

const liquidityPolicy: Policy = {
  ...marketPolicy,
  permissions: ["manage-liquidity", "collect-fees", "exit-liquidity"],
};

const stewardPolicy: Policy = {
  permissions: ["delegate", "restrict", "reclaim"],
  allowedTokens: ["Fictional USDC"],
  maxActionAmounts: [units("400000", "Fictional USDC"), units("0", "DEMO-USD")],
  expiresAt: "2026-10-31T23:59:59.000Z",
  poolId: previewPoolId,
};

const reservePolicy: Policy = {
  permissions: ["reclaim"],
  allowedTokens: ["Fictional USDC"],
  maxActionAmounts: [units("150000", "Fictional USDC"), units("0", "DEMO-USD")],
  expiresAt: "2026-10-18T23:59:59.000Z",
  poolId: previewPoolId,
};

const scoutPolicy: Policy = {
  permissions: ["swap"],
  allowedTokens: ["Fictional USDC"],
  maxActionAmounts: [units("150000", "Fictional USDC"), units("0", "DEMO-USD")],
  expiresAt: "2026-10-18T23:59:59.000Z",
  poolId: previewPoolId,
};

const previewSource = "preview" as const;

export const previewNodes: readonly VaultNode[] = [
  {
    id: "root",
    parentId: null,
    rootId: "root",
    ensName: "main.preview",
    label: "Main agent",
    agentAddress: "0x71e4…A91c",
    vaultAddress: "0x9b20…44d2",
    depth: 0,
    state: "active",
    runtime: "not-connected",
    freeCapital: [units("1462500", "Fictional USDC"), units("892400", "DEMO-USD")],
    tokenHoldings: [units("2862500", "Fictional USDC"), units("1292400", "DEMO-USD")],
    capitalReceivedFromParent: [],
    localPolicy: rootPolicy,
    inheritedConstraints: [],
    effectivePolicy: rootPolicy,
    authorizedPermissions: rootPolicy.permissions,
    position: null,
    source: previewSource,
  },
  {
    id: "market",
    parentId: "root",
    rootId: "root",
    ensName: "operations.main.preview",
    label: "Operations agent",
    agentAddress: "0x0e55…7F11",
    vaultAddress: "0xc450…C806",
    depth: 1,
    state: "active",
    runtime: "not-connected",
    freeCapital: [units("370000", "Fictional USDC"), units("182500", "DEMO-USD")],
    tokenHoldings: [units("1060000", "Fictional USDC"), units("382500", "DEMO-USD")],
    capitalReceivedFromParent: [units("690000", "Fictional USDC"), units("200000", "DEMO-USD")],
    localPolicy: marketPolicy,
    inheritedConstraints: [{ ancestorId: "root", ancestorLabel: "Main agent", policy: rootPolicy }],
    effectivePolicy: marketPolicy,
    authorizedPermissions: marketPolicy.permissions,
    position: null,
    source: previewSource,
  },
  {
    id: "scout",
    parentId: "market",
    rootId: "root",
    ensName: "scout.operations.main.preview",
    label: "Market scout",
    agentAddress: "0x339a…EF05",
    vaultAddress: "0x5C87…0B13",
    depth: 2,
    state: "active",
    runtime: "not-connected",
    freeCapital: [units("83000", "Fictional USDC"), units("46100", "DEMO-USD")],
    tokenHoldings: [units("208000", "Fictional USDC"), units("96100", "DEMO-USD")],
    capitalReceivedFromParent: [units("125000", "Fictional USDC"), units("70000", "DEMO-USD")],
    localPolicy: scoutPolicy,
    inheritedConstraints: [
      { ancestorId: "root", ancestorLabel: "Main agent", policy: rootPolicy },
      { ancestorId: "market", ancestorLabel: "Operations agent", policy: marketPolicy },
    ],
    effectivePolicy: scoutPolicy,
    authorizedPermissions: scoutPolicy.permissions,
    position: null,
    source: previewSource,
  },
  {
    id: "liquidity",
    parentId: "market",
    rootId: "root",
    ensName: "liquidity.operations.main.preview",
    label: "Liquidity agent",
    agentAddress: "0x3a2f…6c99",
    vaultAddress: "0x3190…c8e7",
    depth: 2,
    state: "active",
    runtime: "not-connected",
    freeCapital: [units("196000", "Fictional USDC"), units("136000", "DEMO-USD")],
    tokenHoldings: [units("596000", "Fictional USDC"), units("336000", "DEMO-USD")],
    capitalReceivedFromParent: [units("400000", "Fictional USDC"), units("200000", "DEMO-USD")],
    localPolicy: liquidityPolicy,
    inheritedConstraints: [
      { ancestorId: "root", ancestorLabel: "Main agent", policy: rootPolicy },
      { ancestorId: "market", ancestorLabel: "Operations agent", policy: marketPolicy },
    ],
    effectivePolicy: liquidityPolicy,
    authorizedPermissions: liquidityPolicy.permissions,
    position: { tokenId: "18", liquidity: "42800" },
    source: previewSource,
  },
  {
    id: "steward",
    parentId: "root",
    rootId: "root",
    ensName: "steward.main.preview",
    label: "Capital manager",
    agentAddress: "0x883c…2e71",
    vaultAddress: "0x7701…C192",
    depth: 1,
    state: "active",
    runtime: "not-connected",
    freeCapital: [units("250000", "Fictional USDC")],
    tokenHoldings: [units("650000", "Fictional USDC")],
    capitalReceivedFromParent: [units("400000", "Fictional USDC")],
    localPolicy: stewardPolicy,
    inheritedConstraints: [{ ancestorId: "root", ancestorLabel: "Main agent", policy: rootPolicy }],
    effectivePolicy: stewardPolicy,
    authorizedPermissions: stewardPolicy.permissions,
    position: null,
    source: previewSource,
  },
  {
    id: "reserve",
    parentId: "steward",
    rootId: "root",
    ensName: "reserve.steward.main.preview",
    label: "Reserve agent",
    agentAddress: "0x8ac7…2dd4",
    vaultAddress: "0x8053…F31a",
    depth: 2,
    state: "active",
    runtime: "not-connected",
    freeCapital: [units("125000", "Fictional USDC")],
    tokenHoldings: [units("285000", "Fictional USDC")],
    capitalReceivedFromParent: [units("180000", "Fictional USDC")],
    localPolicy: reservePolicy,
    inheritedConstraints: [
      { ancestorId: "root", ancestorLabel: "Main agent", policy: rootPolicy },
      { ancestorId: "steward", ancestorLabel: "Capital manager", policy: stewardPolicy },
    ],
    effectivePolicy: reservePolicy,
    authorizedPermissions: reservePolicy.permissions,
    position: null,
    source: previewSource,
  },
];

const previewActivity: readonly CapitalActivity[] = [
  {
    id: "a-01",
    kind: "capital-assigned",
    nodeId: "market",
    nodeLabel: "Operations agent",
    description: "Capital delegated from Main agent",
    amount: units("690000", "Fictional USDC"),
    timestamp: "2026-09-25T09:42:00.000Z",
    source: previewSource,
  },
  {
    id: "a-05",
    kind: "capital-assigned",
    nodeId: "steward",
    nodeLabel: "Capital manager",
    description: "Preview allocation from Main agent to a custody mandate",
    amount: units("400000", "Fictional USDC"),
    timestamp: "2026-09-25T09:31:00.000Z",
    source: previewSource,
  },
  {
    id: "a-02",
    kind: "swap",
    nodeId: "scout",
    nodeLabel: "Market scout",
    description: "Preview swap · Fictional USDC → DEMO-USD",
    amount: units("8200", "Fictional USDC"),
    timestamp: "2026-09-25T09:16:00.000Z",
    source: previewSource,
  },
  {
    id: "a-03",
    kind: "position-opened",
    nodeId: "liquidity",
    nodeLabel: "Liquidity agent",
    description: "Opened Fictional USDC / DEMO-USD position",
    timestamp: "2026-09-25T08:51:00.000Z",
    source: previewSource,
  },
  {
    id: "a-06",
    kind: "capital-reclaimed",
    nodeId: "reserve",
    nodeLabel: "Reserve agent",
    description: "Preview return of available capital to its parent vault",
    amount: units("20000", "Fictional USDC"),
    timestamp: "2026-09-24T17:20:00.000Z",
    source: previewSource,
  },
  {
    id: "a-04",
    kind: "policy-tightened",
    nodeId: "reserve",
    nodeLabel: "Reserve agent",
    description: "Action ceiling narrowed by parent",
    timestamp: "2026-09-24T17:08:00.000Z",
    source: previewSource,
  },
];

export const previewDashboard: DashboardData = {
  source: previewSource,
  activitySource: "preview",
  chainId: 11155111,
  rootId: "root",
  rootOwner: null,
  rootOperator: null,
  contractsConfigured: false,
  nodes: previewNodes,
  activity: previewActivity,
  positions: [
    {
      id: "#018",
      nodeId: "liquidity",
      poolLabel: "Fictional USDC / DEMO-USD · 0.30%",
      state: "open",
      liquidity: "42,800",
      token0: units("138500", "Fictional USDC"),
      token1: units("92200", "DEMO-USD"),
      fees0: units("1260", "Fictional USDC"),
      fees1: units("830", "DEMO-USD"),
      source: previewSource,
    },
  ],
};
